import Script from "next/script";

export const metadata = {
  title: "ScholarVault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <>
          <link
            rel="shortcut icon"
            type="image/png"
            href="/assests/icons/icon.png"
          />
          {/* Stylesheet */}
          <link href="/assests/vendor/animate/animate.css" rel="stylesheet" />
          <link
            href="/assests/vendor/magnific-popup/magnific-popup.css"
            rel="stylesheet"
          />
          <link
            href="/assests/vendor/swiper/swiper-bundle.min.css"
            rel="stylesheet"
          />
          {/* Custom Stylesheet */}
          <link rel="stylesheet" href="/assests/css/style.css" />
          <link
            className="skin"
            rel="stylesheet"
            href="/assests/css/skin/skin-1.css"
          />
          {/* Google Fonts */}
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin=""
          />
         {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" /> */}

          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
            rel="stylesheet"
          />

          {/* <link
            rel="shortcut icon"
            type="image/png"
            href="/dash/images/favicon.png"
          />
          <link
            href="/dash/vendor/bootstrap-select/dist/css/bootstrap-select.min.css"
            rel="stylesheet"
          />
          <link href="/dash/css/style.css" rel="stylesheet" /> */}
        </>
        <div>{children}</div>
        <>
          <Script src="/assests/js/jquery.min.js"></Script>
          <Script src="/assests/js/anm.js"></Script>
          <Script src="/assests/vendor/wow/wow.js"></Script>
          <Script src="/assests/vendor/swiper/swiper-bundle.min.js"></Script>
          <Script src="/assests/vendor/bootstrap/js/bootstrap.bundle.min.js"></Script>
          <Script src="/assests/vendor/magnific-popup/magnific-popup.js"></Script>
          <Script src="/assests/js/dz.carousel.js"></Script>
          <Script src="/assests/js/dz.ajax.js"></Script>
          <Script src="/assests/js/custom.js"></Script>
          
          {/* <Script src="/dash/vendor/global/global.min.js"></Script>
          <Script src="/dash/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></Script>
          <Script src="/dash/js/custom.min.js"></Script>
          <Script src="/dash/js/dlabnav-init.js"></Script> */}
        </>
      </body>
    </html>
  );
}
